Add test report

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -23,7 +23,13 @@ jobs:
         if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
     - name: Test with pytest
       run: |
-        pytest tests/ --cov=spike --cov-report=xml
+        pytest tests/ --cov=spike --cov-report=xml --junit-xml=junit.xml
+
+    - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'junit.xml'
     - name: Code Coverage Report
       uses: irongut/CodeCoverageSummary@v1.3.0
       with:
